### ISSUE TITLE
Support custom image-build commands

### ISSUE THREAD

**Issue by aivtsan** [adobe-platform/porter#137]
Rather than use the default image build command with the pipe (as described [here](https://github.com/adobe-platform/porter/blob/master/docs/detailed_design/docker-builder-pattern.md)), we would like to provide our own custom build commands. 

This will allow services to have a code build step that is separated from the runtime-image build step. 

An example for custom build commands would be: 
``docker build -t -v m2:/root/.m2 -v `pwd`:/build $(sha) -f Dockerfile.build .``
`docker build --tag $(defaultRegistry) .`
Which is what we can do today in MT.

**Comment by jfieber** [comment]
The pipeline build strategy is strictly opt in based on the presence of a `Dockerfile.build`.  If you name the dockerfile for your first build step something else, you can configure your CI system to run that before calling `porter build pack` which will invoke the second.

**Comment by aivtsan** [comment]
Thanks @jfieber, i wasn't aware of this option. I'll give it a try!

**Comment by aivtsan** [comment]
Reopening this issue: what we would like is to be able to use volume mount while running the build dockerfile. The reason is that we want to use cached maven repo, rather than having to download all the dependencies each time. These are the commands that we want to use to build our service:
```
docker build -t build-image -f Dockerfile.build .
docker run -it -v m2:/root/.m2 -v `pwd`:/build build-image
```
I think currently this is not possible, since Porter will call the docker run command in 'pack' and it is not configurable (let me know if i'm wrong here).
Ideally, we'd like to be able to define these in a makefile, and have Porter accept a makefile target in the porter config, and that will be used by the 'pack' command (similar to what is currently happening in ETHOS multi-tenant)

**Comment by phylake** [comment]
@aivtsan you can accomplish this w/o new functionality or a new dependency

In your build image download your maven dependencies in such a way that the image layer will be cached. Since this will be cached forever on each host porter runs on you'll need a way to bust the cache periodically.

In your build image `CMD` add `/root/.m2` to the tar command so it's streamed into the runtime image's docker context. Adding a volume map would mean introducing additional host-level dependencies that aren't needed given that we have a full build environment described in docker.
