### ISSUE TITLE
Porter v4.1.1 does not support cloud formation Ref mappings of autoscaling group MinSize, MaxSize values.

### ISSUE THREAD

**Issue by gregoryfischer** [adobe-platform/porter#159]
CloudFormation Map:

    "EnvironmentToMinInstanceValue": {
      "ap-northeast-1": {
        "dev": "1",
        "Stage": "3",
        "Production": "8"
      },
      "eu-west-1": {
        "dev": "1",
        "Stage": "3",
        "Production": "8"
      },
      "us-east-1": {
        "dev": "1",
        "Stage": "5",
        "Production": "10"
      },
      "us-west-2": {
        "dev": "1"
      }
    }

AutoScalingGroup:

    "AutoscalingGroup": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties": {
        "MinSize" : {
          "Fn::FindInMap": [
            "EnvironmentToMinInstanceValue",
            {
              "Ref": "AWS::Region"
            },
            {
              "Ref": "PorterEnvironment"
            }
          ]
        }

Results:

22:41:57 EROR[12-13|22:41:57] MinSize exists but is not a float64 or string porter_version=v4.1.1 cmd=provision Region=ap-northeast-1 MinSize="map[Fn::FindInMap:[EnvironmentToMinInstanceValue map[Ref:AWS::Region] map[Ref:PorterEnvironment]]]" stack="[github.com/adobe-platform/porter/provision/map_resource.go:630 github.com/adobe-platform/porter/provision/map_resource.go:127 github.com/adobe-platform/porter/provision/stack_creator.go:531 github.com/adobe-platform/porter/provision/stack_creator.go:507 github.com/adobe-platform/porter/provision/stack_creator.go:417 github.com/adobe-platform/porter/provision/stack_creator.go:102 github.com/adobe-platform/porter/provision/api.go:183]"

**Comment by vineethguna** [comment]
is this fixed, i still find the same issue in porter v4.9.0

**Comment by phylake** [comment]
No this isn't fixed

**Comment by matt-wormley** [comment]
what is the workaround here?

**Comment by phylake** [comment]
The best workaround isn't ideal but would definitely work. In a [`pre-pack` hook](https://github.com/adobe-platform/porter/blob/master/docs/detailed_design/hooks/pre-pack.md) (**notice** one of the use cases is config generation) you could have the values that are usually `Ref` be, for example, mustache templates.

So instead of a 
```
"AutoscalingGroup": {
  "Type": "AWS::AutoScaling::AutoScalingGroup",
  "Properties": {
    "MinSize" : {
      "Fn::FindInMap": [
        "EnvironmentToMinInstanceValue",
        {
          "Ref": "AWS::Region"
        },
        {
          "Ref": "PorterEnvironment"
        }
      ]
    }
```

You could do
```
"AutoscalingGroup": {
  "Type": "AWS::AutoScaling::AutoScalingGroup",
  "Properties": {
    "MinSize" : {{ap-northeast.dev.minSize}}
  }
}
```

The value replacement would happen as part of template render instead of Cloudformation Refs. The mappings would still exist they would just be outside of the Cloudformation template.

**Comment by matt-wormley** [comment]
aha good stuff. I was looking for something at this level. thanks I'll give that a go.

**Comment by matt-wormley** [comment]
So (just learning this stuff) I actually want to pre-process the cfn.json during `porter build provision` according to the PORTER_ENVIRONMENT setting... so in my case is it correct that I want to render the cfn.json template in `pre-provision`?

**Comment by matt-wormley** [comment]
@phylake can you confirm that your `pre-pack hook` solution would work with the OP's example? He includes `"Ref": "PorterEnvironment"` and am I right that this is not available during the `pre-pack` phase?

**Comment by phylake** [comment]
@matt-wormley the only opportunity to generate the config is in `pre-pack` which isn't specific to any environment. The `"Ref"` isn't useful since any mappings and related CFN functions are only used during `cloudformation:CreateStack` which is well after you need to inject your config values.

If you're going with my templating suggestion then you'd generate in `pre-pack` a CFN template for each environment and point `stack_definition_path` to them

**Comment by matt-wormley** [comment]
I did just that with a template creating different cfn.json files that are specified as `stack_definition_path`. Thanks!
