### ISSUE TITLE
HAProxy Tt times don't make sense

### ISSUE THREAD

**Issue by phylake** [adobe-platform/porter#160]
/cc @ShannonHickey 

https://cbonte.github.io/haproxy-dconv/1.5/configuration.html#8.2.3

**Comment by jfieber** [comment]
Tt don't make sense when haproxy is behind ELB because ELB maintains a pool of open connections to backends such than when a request comes through it doesn't have to make the TCP handshake to the backend end in-band of the request processing.   Because of this, from haproxy's perspective, connections can be opened long before request data comes through the pipe.

This pre-request connection time shows up in the Tq factor haproxy metric, so anything that includes Tq will be thrown off.  The best approximation for Tt is Tt - Tq.

**Comment by phylake** [comment]
Of course! Thanks @jfieber I was helping Shannon debug and got hung up on request sizes (for image uploads)
