### ISSUE TITLE
Logging configuration

### ISSUE THREAD

**Issue by phylake** [adobe-platform/porter#84]
@apratina @aivtsan @jfieber Now that porter is using docker 1.11 we have access to more [logging driver options](https://docs.docker.com/engine/admin/logging/overview/#/syslog-options). I _think_ we need to coordinate `--log-opt syslog-format=[rfc5424|rfc5424micro|rfc3164]` with [$ActionFileDefaultTemplate](https://github.com/adobe-platform/porter/blob/d8c02b7b184e228b7b40db875a8b8e7d4c030380/files/rsyslog-porter.conf#L20)

**Comment by aivtsan** [comment]
@phylake, for messages coming from ASR (and i'm sure the same is true for other projects too), ASR already outputs the logs to stdout in the desired format, including timestamp and other context. Ideally we would like to have the messages coming from the service to be logged as they are without adding prefixes or other data, and ideally they should have a separate 'source' in splunk, so that it's easy to filter out just the logs coming from the service.
Does that make sense?

**Comment by apratina** [comment]
:+1: for what aya already described. Can we also set default configuration to use?
https://git.corp.adobe.com/ASR/opscode/blob/master/bin/rsyslog.sh#L49

**Comment by phylake** [comment]
@jfieber What do you think? There are number of possible configurations and I want to push as much into porter (i.e. out of splunk) as we can

**Comment by jfieber** [comment]
Oh, my.  Where to start with rsyslog…  Have a look at [this](https://git.corp.adobe.com/Stormcloud/f5-api/blob/master/.porter/hooks/etc/rsyslog_bootstrap.sh) for hackery needed for ccweb.  Things of note:
- `$MaxMessageSize` doesn't do squat in `/etc/rsyslog.d/21-porter.conf` because it is specified too late in the config, hence the sed injection near the head.
- Likewise, any config in `/etc/rsyslog.d/*` was loaded too late to divert `local5` out of `/var/log/messages`.
- The version of rsyslog on the CIS AMIs is absolutely prehistoric.

So, in general, adding stuff via `/etc/rsyslog.d/*` is insufficient because of strict order-of-operations constraints.  Once I get some golang stacks ready for porter v2, I may be able to dig into logging a bit more because the current state of things doesn't work particularly well.

It would be _really nice_ to entirely bypass rsyslog… http://blogs.splunk.com/2016/02/10/there-is-a-log-introducing-splunk-logging-driver-in-docker-1-10-0/

**Comment by phylake** [comment]
@jfieber 

> It would be really nice to entirely bypass rsyslog

It would certainly make my life easier but rsyslog is the lowest common denominator. We need logs from HAProxy, cloud-init, cfn-init, cfn-hup, and the ability for custom utilities to log as well. I'm interested in fluentd as a possible (full?) replacement for rsyslog but I know nothing about it.
